keys:
  # Replace with your actual age public key after running: age-keygen -o /persist/sops/age/keys.txt
  - &groot age1es2p8zvt5l6mexc9wwmjt2va2f2twes0yxjwp8m9nxpa8mq65s5se2axhn

creation_rules:
  - path_regex: secrets/secrets-groot.yaml
    key_groups:
      - age:
          - *groot
