{
  imports = [
    ./hyperland
    ./lf
    ./neovim
    ./podman
    ./waybar
    ./alacritty.nix
    ./bash.nix
    ./dconf.nix
    ./desktop.nix
    ./firefox.nix
    ./fish.nix
    ./gtk.nix
    ./gnome.nix
    ./hyprlock.nix
    ./hypridle.nix
    ./kitty.nix
    ./starship.nix
    ./swayidle.nix
    ./swaylock.nix
    ./wezterm.nix
    ./wofi.nix
    ./zsh.nix
    ./yazi.nix
    ./foot.nix
    ./tmux.nix
  ];
}
