{
  imports = [
    ./attic.nix
    ./acme.nix
    ./backrest.nix
    ./copyparty.nix
    ./filen-webdav.nix
    ./gaming.nix
    ./gnome.nix
    ./harmonia.nix
    ./hyprland.nix
    ./locale_keymap.nix
    ./networking.nix
    ./nix-settings.nix
    ./nvidia.nix
    ./power.nix
    ./printing.nix
    ./services.nix
    ./sops.nix
    ./sound.nix
    ./virtualization
    ./podman
    ./specialisation.nix
    ./telegraf.nix
  ];
}
